In [1]:
from numpy import *
a = arange(15).reshape(3,5)


In [3]:
a = arange(15)

In [4]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [6]:
a.reshape(3,5)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

arange(15)生成0~14的连续的数据,一维的. reshape(m,n),将a转换成m*n大小的

In [8]:
a.ndim

2

In [9]:
a.shape

(3, 5)

In [10]:
a.size

15

In [11]:
a.dtype

dtype('int64')

In [13]:
a.dtype.name

'int64'

In [14]:
a.itemsize

8

itemsize表示元素的大小,单位是字节byte

In [15]:
type(a)

numpy.ndarray

In [16]:
b = array([6,7,8])
b
type(b)

numpy.ndarray

使用array来构造ndarray数据,参数是python的List类型

In [17]:
c = array([4.6,1.0,3])

In [18]:
b.dtype.name

'int64'

In [19]:
c.dtype.name

'float64'

In [20]:
a = array(1,2,3,4)

ValueError: only 2 non-keyword arguments accepted

array接收的是个list,不能直接用array(1,2,3)来构造数据.

In [21]:
a = array([(1,2,3),(4,5,6)])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [22]:
a = array[(1,2,3),(3,4)]
a

TypeError: 'builtin_function_or_method' object is not subscriptable

In [23]:
a = array([[1,2,3],[4,5]])

In [24]:
a

array([[1, 2, 3], [4, 5]], dtype=object)

In [25]:
a = array([1.45,1.65,5.6],dtype = int64)

In [26]:
a

array([1, 1, 5])

In [27]:
a = array([(1.45,1.65,5.6)],dtype = int64)

In [28]:
a

array([[1, 1, 5]])

In [29]:
a = array([[1,2,3],[4,5]])
a.size

2

In [30]:
a.shape

(2,)

In [32]:
a = array([[1,2,3],[4,5,6]])

In [33]:
a.shape

(2, 3)

In [34]:
a.size

6

In [35]:
a = array([[1,2,3]])

In [36]:
a.shape

(1, 3)

In [37]:
a = array([(1,2,3),(4,5,6)])
a.shape

(2, 3)

In [38]:
a = array([(1,2,3)])
a.shape

(1, 3)

In [39]:
a

array([[1, 2, 3]])

//array接收的是list,而list的元素可以是多个list,也可以是tuple

In [41]:
zeros((3,4))

array([[ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.]])

In [42]:
ones((2,3,4),dtype=int16)

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int16)

In [46]:
empty((2,3))

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [48]:
empty([2,3])

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

empty和zeros不一样,empty只是初始化给定大小的数组,但是并不会把元素指定为0,需要用户手动设置

In [50]:
arange(10,30,5)

array([10, 15, 20, 25])

10~30的数据,间隔为5

In [51]:
linspace(0,2,9)

array([ 0.  ,  0.25,  0.5 ,  0.75,  1.  ,  1.25,  1.5 ,  1.75,  2.  ])

0~2中9个数

In [52]:
a = linspace(0,2,9)
print a

SyntaxError: Missing parentheses in call to 'print' (<ipython-input-52-cb7bf6b39d0e>, line 2)

In [53]:
print (a)

[[1 2 3]]


In [54]:
a

array([[1, 2, 3]])

In [56]:
a = linspace(0,2,10)

In [58]:
a

array([ 0.        ,  0.22222222,  0.44444444,  0.66666667,  0.88888889,
        1.11111111,  1.33333333,  1.55555556,  1.77777778,  2.        ])

In [59]:
print a

SyntaxError: Missing parentheses in call to 'print' (<ipython-input-59-9d7b17ad5387>, line 1)

In [60]:
print (a)

[ 0.          0.22222222  0.44444444  0.66666667  0.88888889  1.11111111
  1.33333333  1.55555556  1.77777778  2.        ]


In [63]:
print (arange(10000))

[   0    1    2 ..., 9997 9998 9999]


In [64]:
print (arange(10000).reshape(100,100))

[[   0    1    2 ...,   97   98   99]
 [ 100  101  102 ...,  197  198  199]
 [ 200  201  202 ...,  297  298  299]
 ..., 
 [9700 9701 9702 ..., 9797 9798 9799]
 [9800 9801 9802 ..., 9897 9898 9899]
 [9900 9901 9902 ..., 9997 9998 9999]]


In [69]:
set_printoptions(threshold=10)

In [70]:
print (arange(10))

[0 1 2 3 4 5 6 7 8 9]


In [71]:
a = array([1,2,3,4])
b = arange(4)
c = a-b
print (c)

[1 1 1 1]


In [73]:
print (10*sin(a))

[ 8.41470985  9.09297427  1.41120008 -7.56802495]


In [76]:
a = array([[1,1],[1,1]])
b = a
c = a.dot(b)
d = a*b
print (c)
print (d)

[[2 2]
 [2 2]]
[[1 1]
 [1 1]]


In [77]:
b += a
print (b)

[[2 2]
 [2 2]]


In [78]:
b.sum(axis=0)

array([4, 4])

In [79]:
b.sum(axis=1)

array([4, 4])

In [93]:
b = array([(3,2),(1,4)])

In [94]:
b.sum(axis=0)

array([4, 6])

In [95]:
b.sum(axis=1)

array([5, 5])

In [96]:
b.min(axis=0)

array([1, 2])

In [97]:
b.min(axis=1)

array([2, 1])

Universal Functions

In [98]:
B = arange(3)

In [99]:
exp(B)

array([ 1.        ,  2.71828183,  7.3890561 ])

In [100]:
sqrt(B)

array([ 0.        ,  1.        ,  1.41421356])

In [101]:
C = array([2,-1,0])

In [102]:
add(B,C)

array([2, 0, 2])

**数组的索引**

In [103]:
a = arange(10)**3

In [105]:
a

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729])

In [106]:
a[2]

8

In [107]:
a[2:5]

array([ 8, 27, 64])

In [109]:
a[:6:1]

array([  0,   1,   8,  27,  64, 125])

In [110]:
a[: : -1]

array([729, 512, 343, 216, 125,  64,  27,   8,   1,   0])

In [111]:
a[: : 1]

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729])

In [112]:
a[:6:-1]

array([729, 512, 343])

In [114]:
def f(x,y):
    return 10*x+y

b = fromfunction(f,(5,4),dtype=int)
b

array([[ 0,  1,  2,  3],
       [10, 11, 12, 13],
       [20, 21, 22, 23],
       [30, 31, 32, 33],
       [40, 41, 42, 43]])

In [115]:
indices((5,4),dtype=dtype)

array([[[0, 0, 0, 0],
        [1, 1, 1, 1],
        [2, 2, 2, 2],
        [3, 3, 3, 3],
        [4, 4, 4, 4]],

       [[0, 1, 2, 3],
        [0, 1, 2, 3],
        [0, 1, 2, 3],
        [0, 1, 2, 3],
        [0, 1, 2, 3]]], dtype=object)

In [116]:
b[2,3]

23

In [117]:
b[0:5,1]

array([ 1, 11, 21, 31, 41])

In [118]:
b[-1]

array([40, 41, 42, 43])

In [119]:
b[:]

array([[ 0,  1,  2,  3],
       [10, 11, 12, 13],
       [20, 21, 22, 23],
       [30, 31, 32, 33],
       [40, 41, 42, 43]])

In [120]:
b[1,:]

array([10, 11, 12, 13])

In [121]:
b[1,2]

12

In [122]:
c = arange(24).reshape(2,3,4)

In [123]:
c

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [124]:
c[1]

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [125]:
c[0,1]

array([4, 5, 6, 7])

In [126]:
c[0,...]

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [127]:
c[...]

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [128]:
c[...,2]

array([[ 2,  6, 10],
       [14, 18, 22]])

In [140]:
a = floor(10*random.random((2,2)))

In [141]:
a

array([[ 2.,  8.],
       [ 6.,  9.]])

In [142]:
b = floor(10*random.random((2,2)))

In [143]:
b

array([[ 7.,  9.],
       [ 1.,  0.]])

In [144]:
vstack((a,b))

array([[ 2.,  8.],
       [ 6.,  9.],
       [ 7.,  9.],
       [ 1.,  0.]])

In [145]:
hstack((a,b))

array([[ 2.,  8.,  7.,  9.],
       [ 6.,  9.,  1.,  0.]])

In [146]:
a

array([[ 2.,  8.],
       [ 6.,  9.]])

In [147]:
c = a.view()

In [148]:
c is a

False

In [149]:
c.base is a

True

In [150]:
c.flags.owndata

False

In [151]:
c.shape

(2, 2)

In [152]:
a.shape

(2, 2)

In [153]:
a = arange(12).reshape(3,4)

In [154]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [161]:
c = a.view()

In [162]:
c.shape

(3, 4)

In [163]:
c

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [164]:
c.shape = 2,6

In [165]:
c

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [166]:
a.shape

(3, 4)

In [167]:
d = a

In [168]:
d

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [169]:
d[2,3] = 1234

In [170]:
a[2,3]

1234

In [171]:
d[:]

array([[   0,    1,    2,    3],
       [   4,    5,    6,    7],
       [   8,    9,   10, 1234]])

In [172]:
a

array([[   0,    1,    2,    3],
       [   4,    5,    6,    7],
       [   8,    9,   10, 1234]])

In [173]:
e = a.copy()

In [174]:
e

array([[   0,    1,    2,    3],
       [   4,    5,    6,    7],
       [   8,    9,   10, 1234]])

In [175]:
e[2,3] = 4321

In [176]:
a[2,3]

1234

In [177]:
e[2,3]

4321

In [178]:
a

array([[   0,    1,    2,    3],
       [   4,    5,    6,    7],
       [   8,    9,   10, 1234]])

In [179]:
e

array([[   0,    1,    2,    3],
       [   4,    5,    6,    7],
       [   8,    9,   10, 4321]])

In [182]:
i = array([[0,1],[1,2]])
j = array([[2,3],[1,3]])

In [183]:
a[i,j]

array([[   2,    7],
       [   5, 1234]])

In [184]:
a[0,1]

1

a[i,j],从i中取第一个下标,从j中取第二维的下标

In [186]:
x = array([[0,1],[1,2]])
a[x]

array([[[   0,    1,    2,    3],
        [   4,    5,    6,    7]],

       [[   4,    5,    6,    7],
        [   8,    9,   10, 1234]]])

In [187]:
a[[i,j]]

array([[   2,    7],
       [   5, 1234]])

In [188]:
a[[i],[j]]

array([[[   2,    7],
        [   5, 1234]]])

In [192]:
x = array([[[0,1],[1,2]],[[1,2],[2,1]]])
a[x]

array([[[[   0,    1,    2,    3],
         [   4,    5,    6,    7]],

        [[   4,    5,    6,    7],
         [   8,    9,   10, 1234]]],


       [[[   4,    5,    6,    7],
         [   8,    9,   10, 1234]],

        [[   8,    9,   10, 1234],
         [   4,    5,    6,    7]]]])

In [193]:
x1 = [[1,2],[0,1]]
x2 = array(x1)

In [194]:
type(x1)

list

In [195]:
type(x2)

numpy.ndarray

In [196]:
a[x1]

array([4, 9])

In [197]:
a[x2]

array([[[   4,    5,    6,    7],
        [   8,    9,   10, 1234]],

       [[   0,    1,    2,    3],
        [   4,    5,    6,    7]]])

In [198]:
a

array([[   0,    1,    2,    3],
       [   4,    5,    6,    7],
       [   8,    9,   10, 1234]])

使用下标访问注意:如果a[x]中的x是list,那么每次从list的每个元素中分别取不同维的下标,list元素个数不能超过a的维数.

如果x是np.ndarray,则返回的shape和x是一样的,x中的每个元素为a的下标

In [199]:
a[list(x2)]

array([4, 9])

In [202]:
a[tuple(x2)]

array([4, 9])

In [211]:
x3 = array([[[0,1],[1,1]],[[1,2],[2,0]]])

In [212]:
a[x3]

array([[[[   0,    1,    2,    3],
         [   4,    5,    6,    7]],

        [[   4,    5,    6,    7],
         [   4,    5,    6,    7]]],


       [[[   4,    5,    6,    7],
         [   8,    9,   10, 1234]],

        [[   8,    9,   10, 1234],
         [   0,    1,    2,    3]]]])

In [217]:
a1 = array([1,2])
a2 = array([2,3])
c = a1*a2

In [221]:
a1 = array([1,2])
a2 = array([2,3,4])
a11,a22 = ix_(a1,a2)

In [222]:
a11,a22

(array([[1],
        [2]]), array([[2, 3, 4]]))

In [223]:
c = a11*a22
c

array([[2, 3, 4],
       [4, 6, 8]])

In [224]:
c.transpose()

array([[2, 4],
       [3, 6],
       [4, 8]])

In [225]:
inv(c)

NameError: name 'inv' is not defined

In [226]:
from numpy.linalg import *

In [227]:
inv(c)

LinAlgError: Last 2 dimensions of the array must be square

In [228]:
xc = array([[1,2],[2,3]])

In [229]:
inv(xc)

array([[-3.,  2.],
       [ 2., -1.]])

In [230]:
u = eye(3)

In [231]:
u

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])

In [232]:
eig(u)

(array([ 1.,  1.,  1.]), array([[ 1.,  0.,  0.],
        [ 0.,  1.,  0.],
        [ 0.,  0.,  1.]]))

In [233]:
m = matrix('1,2,3')

In [234]:
m

matrix([[1, 2, 3]])

In [235]:
m.T()

TypeError: 'matrix' object is not callable

In [236]:
m.T

matrix([[1],
        [2],
        [3]])

In [238]:
a = matrix([1,3])
b = matrix([2,6])
c = a*b.T
c

matrix([[20]])

In [239]:
arr = array([[1,2,3],[3,4,5]])
ma = mat(arr.copy())

In [241]:
arr.shape,ma.shape

((2, 3), (2, 3))

In [242]:
type(arr),type(ma)

(numpy.ndarray, numpy.matrixlib.defmatrix.matrix)

In [243]:
arr[0,0],ma[0,0]

(1, 1)

In [244]:
arr[0,0]

1

In [245]:
arr[:0]

array([], shape=(0, 3), dtype=int64)

In [246]:
arr[:,0]

array([1, 3])

In [249]:
ma[:,0]

matrix([[1],
        [3]])

> http://scipy.github.io/old-wiki/pages/Tentative_NumPy_Tutorial#Prerequisites

**什么是randomState，随机数发生器**

In [7]:
import numpy as np
np.random.seed(0)
np.random.rand(4)

array([ 0.5488135 ,  0.71518937,  0.60276338,  0.54488318])

In [6]:
np.random.seed(0)
np.random.rand(4)

array([ 0.5488135 ,  0.71518937,  0.60276338,  0.54488318])

如果每次都把seed复位，那么rand相同的数每次产生都是相同的随机数
如果不复位，rand相同的数产生不同的随机数

In [8]:
np.random.seed(0)
np.random.rand(4)

array([ 0.5488135 ,  0.71518937,  0.60276338,  0.54488318])

In [9]:
np.random.rand(4)

array([ 0.4236548 ,  0.64589411,  0.43758721,  0.891773  ])

***